version: '3'

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - django_app

  django_app:
    image: django_app
    build:
      context: ./project1
    container_name: "django_app"
    ports:
      - 8001:8001
    command: gunicorn project1.wsgi --bind 0.0.0.0:8001
    depends_on:
      - db
  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=test_db