apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: developer9844/webapp:2.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8001
